### ISSUE TITLE
A reader predicate that references both partitioned and non-partitioned keys will fail

### ISSUE THREAD

**Issue by selitvin** [uber/petastorm#41] opened 2018-08-12 06:58 UTC
For example the following test will fail (test_end_to_end)
```python
def test_predicate_on_multiple_fields(self):
    expected_values = {'id': 0, 'id2': 0, 'partition': 'p_0'}
    reader = Reader(dataset_url=EndToEndDatasetToolkitTest._dataset_dir, shuffle=False,
                    reader_pool=DummyPool(),
                    predicate=EqualPredicate(expected_values))

    actual = reader.fetch(timeout_s=2)
    self.assertEqual(actual.id, expected_values['id'])
    self.assertEqual(actual.id2, expected_values['id2'])

    reader.stop()
    reader.join()
```

**Comment by jsgoller1** [comment] 2019-01-30 18:17
Looking into this.

**Comment by jsgoller1** [comment] 2019-01-31 23:06
@selitvin - unable to reproduce this with the existing test; closing per our conversation.

**Closed by jsgoller1** 2019-01-31 23:06 UTC
Labels: bug
